#!/usr/bin/env python3
"""Generate .claude/skills/ mirrors from .agents/skills/ source files.

Reads all .agents/skills/*/SKILL.md files and generates simplified mirrors
in .claude/skills/<name>/SKILL.md. Each mirror contains a generated header,
skill name, description, trigger rules, and a pointer back to the source of truth.

Supports --check mode for CI validation that mirrors are up to date.

Usage:
    python3 .agents/tooling/generate_skill_mirrors.py          # Generate mirrors
    python3 .agents/tooling/generate_skill_mirrors.py --check   # Verify mirrors are current
"""

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
SOURCE_DIR = REPO_ROOT / ".agents" / "skills"
MIRROR_DIR = REPO_ROOT / ".claude" / "skills"
GENERATED_HEADER_PREFIX = "<!-- Generated from"


def parse_frontmatter(text: str) -> dict:
    """Extract YAML frontmatter fields from a SKILL.md file."""
    fields = {}
    match = re.match(r"^---\s*\n(.*?)\n---", text, re.DOTALL)
    if not match:
        return fields
    for line in match.group(1).splitlines():
        if ":" in line:
            key, _, value = line.partition(":")
            fields[key.strip()] = value.strip()
    return fields


def extract_triggers(text: str) -> str:
    """Extract content under '## When to Use' heading (if present)."""
    match = re.search(
        r"^##\s+When to Use\s*\n(.*?)(?=\n##\s|\Z)", text, re.DOTALL | re.MULTILINE
    )
    if match:
        return match.group(1).strip()
    return ""


def generate_mirror_content(skill_name: str, source_text: str) -> str:
    """Generate simplified mirror SKILL.md content from source."""
    frontmatter = parse_frontmatter(source_text)
    description = frontmatter.get("description", "")
    triggers = extract_triggers(source_text)
    source_path = f".agents/skills/{skill_name}/SKILL.md"

    lines = [
        f"{GENERATED_HEADER_PREFIX} {source_path} -->",
        "",
        f"# {skill_name}",
        "",
        f"**Description**: {description}",
        "",
    ]

    if triggers:
        lines.extend([
            "## When to Use",
            "",
            triggers,
            "",
        ])

    lines.extend([
        "## Source of Truth",
        "",
        f"This file is auto-generated from `{source_path}`.",
        "Do not edit this file directly. Edit the source and re-run:",
        "",
        "```bash",
        "python3 .agents/tooling/generate_skill_mirrors.py",
        "```",
    ])

    return "\n".join(lines) + "\n"


def discover_skills() -> list[tuple[str, Path]]:
    """Find all skills with SKILL.md in .agents/skills/."""
    skills = []
    if not SOURCE_DIR.is_dir():
        return skills
    for entry in sorted(SOURCE_DIR.iterdir()):
        if entry.is_dir() and (entry / "SKILL.md").is_file():
            skills.append((entry.name, entry / "SKILL.md"))
    return skills


def generate_mirrors() -> list[str]:
    """Generate all mirrors. Returns list of generated skill names."""
    skills = discover_skills()
    if not skills:
        print("No skills found in .agents/skills/", file=sys.stderr)
        return []

    generated = []
    for skill_name, source_path in skills:
        source_text = source_path.read_text(encoding="utf-8")
        mirror_content = generate_mirror_content(skill_name, source_text)
        mirror_path = MIRROR_DIR / skill_name / "SKILL.md"
        mirror_path.parent.mkdir(parents=True, exist_ok=True)
        mirror_path.write_text(mirror_content, encoding="utf-8")
        generated.append(skill_name)
        print(f"  Generated: .claude/skills/{skill_name}/SKILL.md")

    return generated


def clean_orphans(current_skills: set[str]) -> list[str]:
    """Remove mirror directories for skills that no longer exist in source."""
    if not MIRROR_DIR.is_dir():
        return []
    orphans = []
    for entry in sorted(MIRROR_DIR.iterdir()):
        if entry.is_dir() and entry.name not in current_skills:
            # Only clean directories that contain a generated SKILL.md
            skill_file = entry / "SKILL.md"
            if skill_file.is_file():
                text = skill_file.read_text(encoding="utf-8")
                if text.startswith(GENERATED_HEADER_PREFIX):
                    skill_file.unlink()
                    entry.rmdir()
                    orphans.append(entry.name)
                    print(f"  Removed orphan: .claude/skills/{entry.name}/")
    return orphans


def check_mirrors() -> bool:
    """Verify all mirrors are up to date. Returns True if all current."""
    skills = discover_skills()
    all_current = True

    for skill_name, source_path in skills:
        source_text = source_path.read_text(encoding="utf-8")
        expected = generate_mirror_content(skill_name, source_text)
        mirror_path = MIRROR_DIR / skill_name / "SKILL.md"

        if not mirror_path.is_file():
            print(f"  MISSING: .claude/skills/{skill_name}/SKILL.md")
            all_current = False
            continue

        actual = mirror_path.read_text(encoding="utf-8")
        if actual != expected:
            print(f"  STALE: .claude/skills/{skill_name}/SKILL.md")
            all_current = False
        else:
            print(f"  OK: .claude/skills/{skill_name}/SKILL.md")

    # Check for orphans
    if MIRROR_DIR.is_dir():
        source_names = {name for name, _ in skills}
        for entry in sorted(MIRROR_DIR.iterdir()):
            if entry.is_dir() and entry.name not in source_names:
                skill_file = entry / "SKILL.md"
                if skill_file.is_file():
                    text = skill_file.read_text(encoding="utf-8")
                    if text.startswith(GENERATED_HEADER_PREFIX):
                        print(f"  ORPHAN: .claude/skills/{entry.name}/")
                        all_current = False

    return all_current


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate .claude/skills/ mirrors from .agents/skills/ sources"
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify mirrors are up to date (exit 0 if current, 1 if stale)",
    )
    args = parser.parse_args()

    if args.check:
        print("Checking skill mirrors...")
        if check_mirrors():
            print("All mirrors are up to date.")
            return 0
        print("Mirrors are out of date. Run without --check to regenerate.")
        return 1

    print("Generating skill mirrors...")
    generated = generate_mirrors()
    if generated:
        source_names = set(generated)
        clean_orphans(source_names)
        print(f"Done. Generated {len(generated)} mirror(s).")
    else:
        print("No skills to generate.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
